# Site settings
title: LOADING...
url: http://cralor.github.io
description: "Fueled by adventure, pizza, technology, and flight."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffffff'

# Footer settings
footer: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: send
#    url: mailto:chris@gullo.io
#  - title: github
#    url: https://github.com/cralor
#  - title: linkedin
#    url: https://www.linkedin.com/in/christophergullo


# Build settings
markdown: kramdown
permalink: pretty
