# Site settings
title: CHRIS GULLO
email: chris@gullo.io
url: http://cgullo.com
description: "Fueled by adventure, pizza, technology, and human flight."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#00d444'

# Footer settings
footer: Christopher Gullo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: send
    url: mailto:chris@gullo.io
  - title: twitter
    url: https://twitter.com/cralor
  - title: github
    url: https://github.com/cralor


# Build settings
markdown: kramdown
permalink: pretty
