# Site settings
title: CHRIS GULLO
email: chris@gullo.io
url: http://cgullo.com
description: "Fueled by adventure, pizza, technology, and flight."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffffff'

# Footer settings
footer: Christopher Gullo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: send
    url: mailto:chris@gullo.io
  - title: twitter
    url: https://twitter.com/cralor
  - title: github
    url: https://github.com/cralor
  - title: linkedin
    url: https://www.linkedin.com/in/christophergullo
  - title: steam
    url: https://steamcommunity.com/id/cralor/


# Build settings
markdown: kramdown
permalink: pretty
